### PR TITLE
add yaml-cpp find<Pkg>.cmake file

### LINKED ISSUE #214: jaeger not building with yaml-cpp
I am building jaeger-cpp with hunter disabled, in which I found that even if CMakeLists configures cmake with JAEGERTRACING_BUILD_CROSSDOCK as ON/OFF that poses no effect on finding yaml-cpp. 

```
option(JAEGERTRACING_COVERAGE "Build with coverage" $ENV{COVERAGE})
option(JAEGERTRACING_BUILD_CROSSDOCK "Build crossdock" $ENV{CROSSDOCK})
cmake_dependent_option(
  JAEGERTRACING_WITH_YAML_CPP "Use yaml-cpp to parse config files" ON
  "NOT JAEGERTRACING_BUILD_CROSSDOCK" ON)

if(JAEGERTRACING_WITH_YAML_CPP)
  hunter_add_package(yaml-cpp)
  # Not `${hunter_config}` because yaml-cpp provides its own
  # yaml-cpp-config.cmake file
  find_package(yaml-cpp CONFIG REQUIRED)
  if(HUNTER_ENABLED)
      list(APPEND LIBS yaml-cpp::yaml-cpp)
  else()
      list(APPEND LIBS yaml-cpp)
  endif()
  list(APPEND package_deps yaml-cpp)
endif()

```
command used: 
```
cmake -DBUILD_TESTING=OFF -DHUNTER_ENABLED=OFF -DCMAKE_FIND_ROOT_PATH=~/ceph-jaeger-primary/ceph/build/external/ -DJAEGERTRACING_WITH_YAML_CPP=ON -DJAEGERTRACING_BUILD_CROSSDOCK=ON .. 
```
output: 

```
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found THRIFT: /home/deepika/ceph-jaeger-primary/ceph/build/external/lib/libthrift.so  
-- Found nlohmann_json: /usr/lib64/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.7.3") 
-- Configuring done
-- Generating done
```

### PR DESCRIPTION
**Pull request by ideepika**
fixes: #214
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

## Which problem is this PR solving?
-

## Short description of the changes
-

### CODE REVIEW

**Comment by ideepika** [comment]
@mdouaihy

**Comment by mdouaihy** [comment]
Hello @ideepika, what is the problem you want to resolve?

**Comment by ideepika** [comment]
Hey @mdouaihy! I am using jaeger without hunter builds using `-DHUNTER_ENABLED=OFF` while doing so with packages installed from distro, CMake is still not able to discover where config.cmake are present; moreover it completely skips setup for yaml-cpp; even if it's a required package, which makes the build fail.
Adding Findyaml-cpp.cmake will make jaeger not look out for config file and ensures that it is either found or reported missing

**Comment by ideepika** [comment]
@mdouaihy ping?

**Pull request closed without merging**
