### PR TITLE
Implemented GitHub Actions workflow for builds on Ubuntu, MacOS and Windows

### PR DESCRIPTION
**Pull request by leozz37**
### GitHub Actions

Implemented a workflow for building the CMake on Ubuntu, macOS, and Windows, and badge to display their status on README.

A successful run can be seen [here](https://github.com/leozz37/jaeger-client-cpp/actions).

Ubuntu
MacOS
Windows

### CODE REVIEW

**Comment by yurishkuro** [comment]
What are the capacity constraints on GH Action executors? Are they per repo or per org?

Right now we're running on Travis and Appveyor, Travis is constrained to 10 concurrent executors for all of jaegertracing org, while Appveyor may not be used by any other repo (perhaps by C# SDK) and I don't know what limits it has.

**Comment by leozz37** [comment]
@yurishkuro sorry for the late response. Based on my experience, it's per repo and you don't have any limits on concurrent executors. I took a quick look at the documentation and didn't find anything about it (maybe I have to take a deeper look).

Btw you have to keep an eye on the billing board. More info [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions).

Screen Shot 2020-10-07 at 23 46 05

**Review by yurishkuro — APPROVED** [review]
OK, doesn't hurt to try

**Comment by leozz37** [comment]
@yurishkuro awesome! I can make a workflow for other Jaeger projects. Would you like it?

**Pull request merged**
