### PR TITLE
Do not allocate 65k buffers for each span

### PR DESCRIPTION
**Pull request by dqminh**
The current code allocates a few 65k buffer (i.e. maxPacketSize) when writing out
thrift::Span which is wasteful, as single span rarely reaches this size. We
noticed a significant memory increase when running under AddressSanitizer.

Instead, use the default 1024 bytes buffer and relies on buffer's growth to deal
with large span.

Signed-off-by: Daniel Dao <dqminh@cloudflare.com>

### CODE REVIEW

**Comment by DavitSo** [comment]
Hi all is this will reduce memory usage in Collector?

**Comment by mdouaihy** [comment]
@DavitSo, do you mean the Jaeger Collector?

**Comment by DavitSo** [comment]
Yes

**Comment by DavitSo** [comment]
Collector received X size Span and store in back end DB(if i'm wrong correct me), If I'm correct does this  affect on this DB size growing.
Thanks,

**Comment by mdouaihy** [comment]
This is an optimisation in the client:
- For now, the thrift sender create a huge buffer at each serialisation of a Span.
- With the change, the buffer created will be of smaller change. This will reduce the memory allocated for the serialisation
- With my suggestion, I am proposing to allocated once the buffer and reuse it.

This should have zero impact on data sent to the Collector.

**Comment by DavitSo** [comment]
ok , thanks for clarification!

**Comment by yurishkuro** [comment]
Reusing the buffer is certainly the right approach, as long as concurrency concerns are taken into account. If it's possible that the sender could be invoked concurrently, then pooling of the buffers could be an option.

**Comment by mdouaihy** [comment]
the sender is not concurrent so the resuing the buffer should be ok

**Comment by dqminh** [comment]
@mdouaihy @yurishkuro apologized for long delay as i took a vacation :D 

I sent another change at https://github.com/jaegertracing/jaeger-client-cpp/pull/185 which reuse the buffer for a sender to calculate the individual thrift sizes, hopefully that's correct.

**Comment by yurishkuro** [comment]
fixed in #185

**Pull request closed without merging**
