### PR TITLE
Update OpenTracing to 1.6.0

### PR DESCRIPTION
**Pull request by mdouaihy**
## Which problem is this PR solving?
- This solves the request #189 

## Short description of the changes
- Update the version of OpenTracing to 1.6.0
- GTest version was fixed to 1.8.0-hunter-p11 because the later versions seem to have a problem with the rpath making the unit test fail because the binaries are unable to locate the gtest libraries. This issue will be followed separately to avoid blocking this request.

This will also solve another problem reported by @Alek86 in #208. This was due to a bug in OpenTracing compile flags that was fixed with the latest release.

### CODE REVIEW

**Comment by mdouaihy** [comment]
Hello @yurishkuro,

Would you please take a look?

**Comment by yurishkuro** [comment]
Travis is failing. I restarted once, it failed with the same errors.

**Comment by mdouaihy** [comment]
This seems to be a technical problem at Travis or Ubuntu package servers level

`
W: The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release' is not signed.
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
`

**Comment by mdouaihy** [comment]
I run Travis on my branch before doing the PR and experienced same errors. I rerun the build and it passed.
https://travis-ci.org/mdouaihy/jaeger-client-cpp/builds/654680113?utm_medium=notification&utm_source=github_status

**Comment by suab321321** [comment]
@yurishkuro the error is still there when I run `cmake ..` from build it shows me this output.
Screenshot from 2020-02-26 23-51-21

the error is in the Gtest packages, so I tried to run the individuallty this package inside inside the directory `/.hunter/_Base/d45d77d/de38925/3b7ee27/Build/GTest` and did `cmake --build Build/` and this is the output I m getting

Screenshot from 2020-02-26 23-56-00

now I dont understand how to fix this

**Pull request merged**
