### PR TITLE
Added support for setting tracer tags via the configuration

### PR DESCRIPTION
**Pull request by tobiasstadler**
## Which problem is this PR solving?
At the moment setting the tracer tags is only possible via an environment variable. It should also be possible to set them via the configuration (file).

## Short description of the changes
* I enhanced the parse the parse method to read a new configuration key for the tracer tags

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@yurishkuro would mind doing a review please?

**Review by yurishkuro — APPROVED** [review]

**Comment by tobiasstadler** [comment]
@yurishkuro The build failure in macOS seems to be unrelated to my change.

**Comment by tobiasstadler** [comment]
@yurishkuro Could you rerun the build please

**Comment by yurishkuro** [comment]
restarted

**Comment by tobiasstadler** [comment]
Thank you! Would you be so kind and do a release please?

**Comment by yurishkuro** [comment]
Released in 0.8.0

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by miry** [comment]
@tobiasstadler Is it working only with Yaml config?

**Pull request merged**
